### ISSUE TITLE
Cannot call method apply of undefined

### ISSUE THREAD

**Issue by straydogstudio** [TrevorBurnham/Jitter#31]
I've installed the latest node, coffeescript, and jitter. I get the following:

```
$ jitter coffee/ js/

/usr/local/lib/node_modules/jitter/node_modules/sink/lib/sink.js:42
    return cb ? func.apply(this, args.concat([function() {
                     ^
TypeError: Cannot call method 'apply' of undefined
    at /usr/local/lib/node_modules/jitter/node_modules/sink/lib/sink.js:42:22
    at Array.0 (/usr/local/lib/node_modules/jitter/node_modules/sink/lib/sink.js:9:14)
    at /usr/local/lib/node_modules/jitter/node_modules/sink/lib/sink.js:20:27
    at /usr/local/lib/node_modules/jitter/lib/jitter.js:111:7
    at Object.run (/usr/local/lib/node_modules/jitter/lib/jitter.js:96:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/jitter/bin/jitter:8:26)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.<anonymous> (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:38)
```

I have the following:
- Mac OSX Mountain Lion
- node 0.6.18
- CoffeeScript 1.6.3

Any suggestions?

**Comment by pconerly** [comment]
That node version is pretty old, the current is node `0.10.32`  I also highly recommend using `nvm` to handle node versions: https://github.com/creationix/nvm

```
$ nvm install 0.6.18
## a bunch of output
[peterconerly@Jitter]$ nvm current
v0.6.18
[peterconerly@Jitter]$ bin/jitter src/ lib/

/Users/peterconerly/code/Jitter/node_modules/sink/lib/sink.js:42
    return cb ? func.apply(this, args.concat([function() {
                     ^
TypeError: Cannot call method 'apply' of undefined
  at call (/Users/peterconerly/code/Jitter/node_modules/sink/lib/sink.js:42:22)
  at Array.q.q [as 0] (/Users/peterconerly/code/Jitter/node_modules/sink/lib/sink.js:9:14)
  at q.q (/Users/peterconerly/code/Jitter/node_modules/sink/lib/sink.js:20:27)
  at compileScripts (/Users/peterconerly/code/Jitter/lib/jitter.js:115:7)
  at Object.exports.run (/Users/peterconerly/code/Jitter/lib/jitter.js:101:12)
  at Object.<anonymous> (/Users/peterconerly/code/Jitter/bin/jitter:8:26)
  at Module._compile (module.js:446:26)
  at Object.Module._extensions..js (module.js:464:10)
  at Module.load (module.js:353:31)
  at Function.Module._load (module.js:311:12)
  at Array.Module.runMain [as 0] (module.js:484:10)
  at EventEmitter.startup.processNextTick.process._tickCallback (node.js:190:38)

[peterconerly@Jitter]$ nvm use 0.10.30
Now using node v0.10.30
[peterconerly@Jitter]$ bin/jitter src/ lib/
Watching for changes and new files. Press Ctrl+C to stop.
```
